---
title: "Prediction of PPI"
author: "Joaquim Aguirre-Plans"
date: "13/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description

Predict the PPI network using gene co-expression networks created from GTEx RNAseq samples.

```{r, message=FALSE}
library(data.table)
library(dplyr)
library(ggplot2)
library(igraph)
library(wTO)
set.seed(1510)
```

## Read files

```{r define_files}
# Define working directories
databases_dir = '/home/j.aguirreplans/Databases'
networks_dir = '/scratch/j.aguirreplans/Scipher/SampleSize/networks_GTEx'
ppi_dir = '/home/j.aguirreplans/data/PPI'
ppi_filt_dir = paste(ppi_dir, 'interactome_tissue_specific', sep='/')

# Define input files
samples_subjects_file = '/home/j.aguirreplans/Databases/GTEx/v8/GTEx_Annotations_SamplesSubjectsMerged.txt'

```

```{r read_files}
# Read input files
samples_df = fread(samples_subjects_file)

```

```{r predict_ppi}
###
### CHECK MINET VALIDATE() FUNCTION TO COMPARE NETWORK TO A REFERENCE NETWORK
### It might be easier
###

roc_df = data.frame(matrix(ncol=7,nrow=0, dimnames=list(NULL, c("tissue", "sex", "size", "rep", "cutoff", "TPR", "FPR"))))
metric = "wgcna"
rep = 1
#rep = 10
cutoffs_list = seq(0.1, 0.9, by = 0.1)
#sex_to_id = data.frame(row.names=c("male","female") , val=c(1,2))
sex_to_id = data.frame(row.names=c("female") , val=c(2))
#tissues = c("Spleen", "Whole.Blood")
tissues = c("Spleen")
for (tissue in tissues){
  for (sex in rownames(sex_to_id)){
    sex_id = sex_to_id[sex,]
    
    # Get samples
    tissue_sex_samples = samples_df[(samples_df$SMTSD.no.sp.char == tissue) & (samples_df$SEX == sex_id),]$SAMPID
    
    if (length(tissue_sex_samples) > 10){
      print(tissue)
      print(sex)

      # Define networks dir
      tissue_sex_networks_dir = paste(networks_dir, paste(tissue, sex, sep="_"), sep='/')
      
      # Read PPI network
      ppi_tissue_sex_filt_file = paste(ppi_filt_dir, paste("interactome_2019_", tissue, "_", sex, ".csv", sep=''), sep='/')
      ppi_tissue_sex_filt_df = fread(ppi_tissue_sex_filt_file) %>% select(proteinA_symbol, proteinB_symbol)
      ppi_tissue_sex_filt_net = graph_from_data_frame(ppi_tissue_sex_filt_df, directed=F) %>% simplify()
      full_ppi_tissue_sex_filt_net = graph(combn(as_ids(V(ppi_tissue_sex_filt_net)),2), directed=FALSE)
      N = gsize(full_ppi_tissue_sex_filt_net) - gsize(ppi_tissue_sex_filt_net)

      
      size_list <- seq(10, length(tissue_sex_samples), 10)
      for (size in size_list){
        
        print(size)
        
        for(r in 1:rep){
          
          print(r)

          # Read gene co-expression network
          tissue_sex_network_file = paste(tissue_sex_networks_dir, paste(metric, "_RNAseq_samples_", tissue, "_", sex, "_size_", as.character(size), "_rep_", as.character(r), ".net", sep=""), sep="/")
          tissue_sex_network_df = as.data.frame(fread(tissue_sex_network_file))
          rownames(tissue_sex_network_df) = colnames(tissue_sex_network_df)
          tissue_sex_network_df = tissue_sex_network_df %>% wTO.in.line() %>% rename(Score=wTO)
          for (cutoff in cutoffs_list){
            print(cutoff)
            tissue_sex_network_filt_df = tissue_sex_network_df[tissue_sex_network_df$Score > cutoff,] %>% select(Node.1, Node.2)
            tissue_sex_network_filt_net = graph_from_data_frame(tissue_sex_network_filt_df, directed=F) %>% simplify()
            intersection_net = intersection(tissue_sex_network_filt_net, ppi_tissue_sex_filt_net)
            intersection_net = delete.vertices(intersection_net, which(degree(intersection_net)==0))
            difference_1_vs_2 = difference(tissue_sex_network_filt_net, ppi_tissue_sex_filt_net)
            P = gsize(tissue_sex_network_filt_net)
            TP = gsize(intersection_net)
            FP = gsize(difference_1_vs_2)
            roc_df = rbind(roc_df, data.frame(tissue=tissue, sex=sex, size=size, rep=r, cutoff=cutoff, TPR=TP/P, FPR=FP/N))

          }
          
        }
        
      }
      
    }
  }
}

```


```{r plot_roc_curve}

roc_merged_df = roc_df[(roc_df$cutoff != 1) & !(roc_df$size %in% c(10, 30, 50, 70)),] %>% group_by(tissue, sex, size, cutoff) %>% summarise(mean(TPR), mean(FPR)) %>% rename("TPR"="mean(TPR)", "FPR"="mean(FPR)") %>% ungroup()
roc_merged_df

roc = ggplot(roc_merged_df, aes(x = FPR, y = TPR)) + 
  geom_line(aes(color = size, group = size))
roc

```





