---
title: "Untitled"
author: "Joaquim Aguirre-Plans"
date: "1/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(dplyr)
library(igraph)
set.seed(1510)
```

```{r}
network_20_samples_file = "/scratch/j.aguirreplans/Scipher/SampleSize/subgraphs_scipher/all_samples/disease_genes/spearman_scipher_all_samples_size_20_rep_1_pvalue_0.05_disp_None_disease_genes_subgraphs/arthritis.rheumatoid.txt"
#network_60_samples_file = "/scratch/j.aguirreplans/Scipher/SampleSize/subgraphs_scipher/all_samples/disease_genes/spearman_scipher_all_samples_size_60_rep_1_pvalue_0.05_disp_None_disease_genes_subgraphs/arthritis.rheumatoid.txt"
network_100_samples_file = "/scratch/j.aguirreplans/Scipher/SampleSize/subgraphs_scipher/all_samples/disease_genes/spearman_scipher_all_samples_size_100_rep_1_pvalue_0.05_disp_None_disease_genes_subgraphs/arthritis.rheumatoid.txt"
network_220_samples_file = "/scratch/j.aguirreplans/Scipher/SampleSize/subgraphs_scipher/all_samples/disease_genes/spearman_scipher_all_samples_size_220_rep_3_pvalue_0.05_disp_None_disease_genes_subgraphs/arthritis.rheumatoid.txt"

network_20_samples = read_graph(file = network_20_samples_file, format = "graphml")
#network_60_samples = read_graph(file = network_60_samples_file, format = "graphml")
network_100_samples = read_graph(file = network_100_samples_file, format = "graphml")
network_220_samples = read_graph(file = network_220_samples_file, format = "graphml")
networks = list("20"=network_20_samples, "100"=network_100_samples, "220"=network_220_samples)

all_degrees = c()
for(network in networks){
  disease_components = igraph::components(network)
  disease_lcc = igraph::induced.subgraph(network, vids = V(network)[disease_components$membership == which.max(disease_components$csize)] )
  V(disease_lcc)$degree <- degree(disease_lcc)
  all_degrees = unique(c(all_degrees, V(disease_lcc)$degree))
}
uni_all <- seq( min(all_degrees), max(all_degrees))
colors <- data.frame( color = heat.colors(length(uni_all), rev = T),
                      levels = uni_all)


```

```{r, echo=FALSE}
for (network_id in names(networks)){
  print(network_id)
  network = networks[[network_id]]
  disease_components = igraph::components(network)
  disease_lcc = igraph::induced.subgraph(network, vids = V(network)[disease_components$membership == which.max(disease_components$csize)] )
  print(gsize(disease_lcc))
  print(gorder(disease_lcc))
  V(disease_lcc)$size = degree(disease_lcc) %>% 
    CoDiNA::normalize()
  V(disease_lcc)$size = (V(disease_lcc)$size + 0.1)*5
  V(disease_lcc)$color =  colors$color[match(degree(disease_lcc), colors$levels)]
  V(disease_lcc)$frame.color = '#006d77'
  V(disease_lcc)$label = NA
  
  #E(disease_lcc)$width = edge.betweenness(disease_lcc, directed = F) %>% CoDiNA::normalize()
  #E(disease_lcc)$width = E(disease_lcc)$width + 0.01
  #E(disease_lcc)$weight = E(disease_lcc)$width
  par(mar = c(0,0,0,0))
  plot(disease_lcc)
  
}

```

```{r, echo=FALSE}
V(network_small_sample_size)$color <- colors$color[match(V(network_small_sample_size)$degree, colors$levels)]
V(network_small_sample_size)$label <- V(network_small_sample_size)$degree
plot(
  network_small_sample_size,
  vertex.size     = degree(network_small_sample_size)/10 +1,
  vertex.label    = NA,
  vertex.label.cex=0.5,
  mode = "fruchtermanreingold",
  main="Main core of network from 10 samples"
  )
```

```{r, echo=FALSE}
V(network_large_sample_size)$color <- colors$color[match(V(network_large_sample_size)$degree, colors$levels)]
V(network_large_sample_size)$label <- V(network_large_sample_size)$degree
V(network_large_sample_size)$label[V(network_large_sample_size)$label == 0] <- NA
plot(
  network_large_sample_size,
  #vertex.size     = degree(network_large_sample_size)/10 +1,
  vertex.label    = NA,
  vertex.label.cex=0.5,
  mode = "fruchtermanreingold",
  main="Main core of network from 580 samples"
  )
```

```{r}
network_small_sample_size_file = "/home/j.aguirreplans/Projects/Scipher/SampleSize/data/out/networks_scipher/all_samples/disease_genes/spearman_scipher_all_samples_size_10_rep_1_edges_100000_disease_genes_subgraphs/arthritis.rheumatoid.txt"
network_large_sample_size_file = "/home/j.aguirreplans/Projects/Scipher/SampleSize/data/out/networks_scipher/all_samples/disease_genes/spearman_scipher_all_samples_size_580_rep_1_edges_100000_disease_genes_subgraphs/arthritis.rheumatoid.txt"
network_small_sample_size = read_graph(file = network_small_sample_size_file, format = "graphml")
network_large_sample_size = read_graph(file = network_large_sample_size_file, format = "graphml")

```

```{r, echo=FALSE}
V(network_small_sample_size)$degree <- degree(network_small_sample_size)
V(network_large_sample_size)$degree <- degree(network_large_sample_size)
all_degrees = c(V(network_small_sample_size)$degree, V(network_large_sample_size)$degree)
uni_all <- seq( min(all_degrees), max(all_degrees))
colors <- data.frame( color = heat.colors(length(uni_all), rev = T),
                      levels = uni_all)
```

```{r, echo=FALSE}
V(network_small_sample_size)$color <- colors$color[match(V(network_small_sample_size)$degree, colors$levels)]
V(network_small_sample_size)$label <- V(network_small_sample_size)$degree
V(network_small_sample_size)$label[V(network_small_sample_size)$label == 0] <- NA
plot(
  network_small_sample_size,
  #vertex.size     = degree(network_small_sample_size)/10 +1,
  vertex.label    = NA,
  vertex.label.cex=0.5,
  mode = "fruchtermanreingold",
  main="Rheumatoid arthritis subgraph of network from 10 samples"
  )
```


```{r, echo=FALSE}
V(network_large_sample_size)$color <- colors$color[match(V(network_large_sample_size)$degree, colors$levels)]
V(network_large_sample_size)$label <- V(network_large_sample_size)$degree
V(network_large_sample_size)$label[V(network_large_sample_size)$label == 0] <- NA
plot(
  network_large_sample_size,
  #vertex.size     = degree(network_large_sample_size)/10 +1,
  vertex.label    = NA,
  vertex.label.cex=0.5,
  mode = "fruchtermanreingold",
  main="Rheumatoid arthritis subgraph of network from 580 samples"
  )
```

