#!/usr/bin/env Rscript
packrat::init("/home/j.aguirreplans/Projects/Scipher/SampleSize/scripts/SampleSizeR")
library(optparse)
require(dplyr)
require(magrittr)
require(data.table)
library(Rcpp)
library(Rfast)
require(dplyr)
require(magrittr)
require(data.table)
require(wTO)
require(parallel)
set.seed(1510)

initial.options <- commandArgs(trailingOnly = FALSE)
scripts.dir <- dirname(sub("--file=", "", initial.options[grep("--file=", initial.options)]))
newwTO.file <- paste(scripts.dir, "99_newwTO.R", sep="/")
coexpression.functions.file <- paste(scripts.dir, "coexpression_functions.R", sep="/")
source(newwTO.file)
source(coexpression.functions.file)
