---
title: "Thorsson analysis"
author: "Joaquim Aguirre-Plans"
date: "4/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description

Analyze TCGA dataset from Thorsson et al.

```{r, message=FALSE}
library(data.table)
library(dplyr)
library(forcats)
library(ggplot2)
require(magrittr)
library(tidyr)
library(igraph)
library(rjson)
set.seed(1510)
`%ni%` <- Negate(`%in%`)
```

## Read files

```{r define_files}
# Define working directories
thorsson_dir = '/home/j.aguirreplans/Databases/TCGA/Thorsson'
thorsson_input_dir = paste(thorsson_dir, 'raw', sep='/')
thorsson_output_dir = paste(thorsson_dir, 'out', sep='/')

# Define input files
subtypes_file = paste(thorsson_input_dir, 'subtypes.csv', sep='/')
types_subtypes_file = paste(thorsson_input_dir, 'types_subtypes.csv', sep='/')
rnaseq_file = paste(thorsson_input_dir, 'rnaseq.tsv', sep='/')

```

```{r read_files}
# Read input files
subtypes_df = fread(subtypes_file, header=TRUE)[,1:11]
types_subtypes_df = fread(types_subtypes_file, header=TRUE)[,1:3]
rnaseq_df = fread(rnaseq_file, header=TRUE)

```

## RNA-seq information

The RNA-seq data is organized os that the row names are samples, and the column names are genes. There are `r ncol(rnaseq_df)` samples and `r ncol(rnaseq_df)` genes

```{r}
nrow(rnaseq_df)
ncol(rnaseq_df)
rnaseq_df[1:5,1:5]

```

## Subjects information

There are `r length(unique(types_subtypes_df$pan.samplesID))` samples.

```{r}
head(types_subtypes_df)
head(subtypes_df)
length(unique(types_subtypes_df$pan.samplesID))
length(unique(subtypes_df$pan.samplesID))
rnaseq_df = rnaseq_df %>% filter(IDS %in% types_subtypes_df$pan.samplesID)

```



