---
title: "TCGA subsampling"
author: "Joaquim Aguirre-Plans"
date: "4/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description

Create subsamples of gene expression data from TCGA (GDC), with the aim of testing the effect of sample size in these subsamples.

```{r, message=FALSE}
library(data.table)
library(dplyr)
library(ggplot2)
require(magrittr)
library(tidyr)
library(igraph)
set.seed(1510)
`%ni%` <- Negate(`%in%`)
```

## Read files

```{r}
# Define working directories
gdc_dir = '/work/ccnr/j.aguirreplans/Databases/TCGA/2022-11-18-Dataset/TCGA'
output_dir = paste(gdc_dir, 'out', sep='/')
sampling_dir = '/home/j.aguirreplans/Projects/Scipher/SampleSize/data/sampling/TCGA/2022-11-18-Dataset'
dir.create(sampling_dir, showWarnings = FALSE)
sampling_dir = paste(sampling_dir, "sampling_with_repetition", sep="/")
dir.create(sampling_dir, showWarnings = FALSE)

# Read sample groups file
sample_groups_file = paste(gdc_dir, paste('raw/metadata/sample_groups.txt', sep=""), sep='/')
sample_groups_df = fread(sample_groups_file)
```

```{r}
head(sample_groups_df)
```

## Subsampling

We define the sampling function:

```{r sampling_function}
## Random sampling with replacement
create_random_subsample_datasets_with_replacement <- function(samples_list, size_list, rep, rnaseq, output_dir, output_file_name){
  subsamples_list = list()
  seed <- 1
  for(size in size_list){
    set.seed(seed)
    seed <- seed + 1
    for(r in 1:rep){
      subsample <- sample(samples_list, size=size, replace=TRUE)
      subsamples_list[[size]] = subsample
      subsample_df = rnaseq %>% filter(Sample %in% subsample)
      output_file = paste(output_dir, paste(paste(output_file_name, 'size', size, 'rep', r, sep='_'), '.txt', sep=''), sep='/')
      subsample_df %>% write.table(output_file, quote = F, sep='\t', row.names = F, col.names = T)
    }
  }
  return(subsamples_list)
}
# Same but without creating the gene expression files, just files with samples
create_random_subsamples_with_replacement <- function(samples_list, size_list, rep, output_dir, output_file_name){
  subsamples_df = data.frame(matrix(ncol=3,nrow=0, dimnames=list(NULL, c("size", "rep", "samples"))))
  seed <- 1
  for(size in size_list){
    set.seed(seed)
    seed <- seed + 1
    for(r in 1:rep){
      subsample <- sort(sample(samples_list, size=size, replace=TRUE))
      subsample_df <- data.frame(samples=subsample)
      output_file = paste(output_dir, paste(paste(output_file_name, 'size', size, 'rep', r, sep='_'), '.txt', sep=''), sep='/')
      subsample_df %>% write.table(output_file, quote = F, sep='\t', row.names = F, col.names = T)
      subsamples_df = rbind(subsamples_df, data.frame(size=size, rep=r, samples=paste(subsample, collapse = ';')))
    }
  }
  return(subsamples_df)
}

```

For all samples, we select groups of samples from different sizes:

```{r}
for(sample_group_type_selected in c("tumor", "normal")){
  # Create directory to store sample groups
  sample_group_type_dir = paste(sampling_dir, sample_group_type_selected, sep='/')
  dir.create(sample_group_type_dir, showWarnings = FALSE)
  tcga_sampling_dir = paste(sample_group_type_dir, "TCGA", sep='/')
  dir.create(tcga_sampling_dir, showWarnings = FALSE)
  # Define available samples
  samples_selected = unique((sample_groups_df %>% filter(sample_group_type == sample_group_type_selected))$participant_sample_type)
  # Define sizes
  size_list <- seq(10, length(samples_selected), 10)
  # Create a file with a list of all samples
  all_samples_output_file = paste(tcga_sampling_dir, paste('tcga_TCGA_all_samples.txt', sep=''), sep='/')
  all_samples_df <- data.frame(samples=samples_selected)
  all_samples_df %>% write.table(all_samples_output_file, quote = F, sep='\t', row.names = F, col.names = T)
  # Create files with lists of subsamples
  output_file_name = 'tcga_TCGA'
  subsamples_df <- create_random_subsamples_with_replacement(samples_list=samples_selected, size_list=size_list, rep=10, output_dir=tcga_sampling_dir, output_file_name=output_file_name)
  # Create a final file with a compilation of all selected samples for the same sample group
  compilation_samples_output_file = paste(sample_group_type_dir, 'tcga_TCGA.txt', sep='/')
  subsamples_df %>% write.table(compilation_samples_output_file, quote = F, sep='\t', row.names = F, col.names = T)
}
```

For each type of sample group, we select groups of samples from different sizes:

```{r}
sex_types = c("male","female", "")
for(sample_group_type_selected in unique(sample_groups_df$sample_group_type)){
  sample_group_type_dir = paste(sampling_dir, sample_group_type_selected, sep='/')
  dir.create(sample_group_type_dir, showWarnings = FALSE)
  sample_group_ids = unique((sample_groups_df %>% filter(sample_group_type == sample_group_type_selected))$sample_group_id)
  for (sample_group_id_selected in sample_group_ids){
    for (sex_selected in sex_types){
      if (sex_selected == ""){
        samples_selected = unique((sample_groups_df %>% filter((sample_group_type == sample_group_type_selected) & (sample_group_id == sample_group_id_selected)))$participant_sample_type)
        sample_group_sampling_dir = paste(sample_group_type_dir, sample_group_id_selected, sep='/')
        all_samples_output_file = paste(sample_group_sampling_dir, paste('tcga_', sample_group_id_selected, '_all_samples.txt', sep=''), sep='/')
        output_file_name = paste(paste(paste('tcga', sample_group_id_selected, sep="_")))
        compilation_samples_output_file = paste(sample_group_type_dir, paste(paste('tcga', sample_group_id_selected, sep="_"), '.txt', sep=''), sep='/')
      } else {
        samples_selected = unique((sample_groups_df %>% filter((sample_group_type == sample_group_type_selected) & (sample_group_id == sample_group_id_selected) & (sex == sex_selected)))$participant_sample_type)
        sample_group_sampling_dir = paste(sample_group_type_dir, paste(sample_group_id_selected, sex_selected, sep="_"), sep='/')
        all_samples_output_file = paste(sample_group_sampling_dir, paste('tcga_', sample_group_id_selected, '_', sex_selected, '_all_samples.txt', sep=''), sep='/')
        output_file_name = paste(paste(paste('tcga', sample_group_id_selected, sex_selected, sep="_")))
        compilation_samples_output_file = paste(sample_group_type_dir, paste(paste('tcga', sample_group_id_selected, sex_selected, sep="_"), '.txt', sep=''), sep='/')
      }
      if (length(samples_selected) > 10){
        # Define list of different sample sizes
        size_list <- seq(10, length(samples_selected), 10)
        dir.create(sample_group_sampling_dir, showWarnings = FALSE)
        # Create a file with a list of all samples
        all_samples_df <- data.frame(samples=samples_selected)
        all_samples_df %>% write.table(all_samples_output_file, quote = F, sep='\t', row.names = F, col.names = T)
        # Create files with lists of subsamples
        subsamples_df <- create_random_subsamples_with_replacement(samples_list=samples_selected, size_list=size_list, rep=10, output_dir=sample_group_sampling_dir, output_file_name=output_file_name)
        # Create a final file with a compilation of all selected samples for the same sample group
        subsamples_df %>% write.table(compilation_samples_output_file, quote = F, sep='\t', row.names = F, col.names = T)
      }
    }
  }
}
```
