---
title: "Strong correlations in ARACNe and GENIE3"
author: "Joaquim Aguirre-Plans"
date: "2024-10-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description

Analysis on strong correlations across sample size using alternative tools (ARACNe and GENIE3).

```{r}
packrat::init("/home/j.aguirreplans/Projects/Scipher/SampleSize/scripts/SampleSizeR")
```

```{r load_libraries}
library(data.table)
library(dplyr)
library(ggplot2)
library(patchwork)
library(wTO)
set.seed(1510)
options(bitmapType='cairo')
```


## Load data

```{r define_paths}
input_dir <- '/home/j.aguirreplans/Projects/Scipher/SampleSize/scripts/SampleSizeShiny/data'
example_dir <- paste(input_dir, 'example_pearson_pval_0.05', sep = "/")
plots_dir <- '/home/j.aguirreplans/Projects/Scipher/SampleSize/data/out/plots'
tables_dir <- '/home/j.aguirreplans/Projects/Scipher/SampleSize/data/out/tables'
font_selected <- "Helvetica"
model_selected <- "Stretched exponential (by linear fit)"
topology_type_normalization <- "divide.L"
datasets_selected = c("gse193677:rectum_uc_inflamed", 
                      "gtex:breast.mammary.tissue",
                      "gtex:lung", 
                      "tcga:tcga-brca_female")
all_datasets <- c(
  "scipher:scipher.sample.per.patient.baseline",
  "gse193677:rectum_cd_inflamed",
  "gse193677:rectum_uc_inflamed",
  "gse193677:rectum_control_noninflamed",
  "gse193677:rectum_inflamed",
  "gse193677:rectum_noninflamed",
  "gtex:breast.mammary.tissue_female",
  "gtex:lung",
  "gtex:skin.sun.exposed.lower.leg",
  "gtex:thyroid",
  "gtex:whole.blood",
  "tcga:tcga-brca_female",
  "tcga:tcga-kirc",
  "tcga:tcga-kirp",
  "tcga:tcga-luad",
  "tcga:tcga-lusc",
  "tcga:tcga-thca",
  "tcga:breast_female", 
  "tcga:kidney",
  "tcga:lung",
  "tcga:brca.luma",
  "tcga:brca.lumb"
)

dataset2name <- c(
  "gtex:breast.mammary.tissue_female" = "GTEx: Breast",
  "gtex:whole.blood" = "GTEx: Whole blood",
  "gtex:lung" = "GTEx: Lung",
  "tcga:tcga-brca_female" = "TCGA: Breast cancer",
  "tcga:tcga-luad" = "TCGA: Lung cancer",
  "scipher:scipher.sample.per.patient.baseline" = "R. arthritis",
  "gse193677:rectum_uc_inflamed" = "UC inflamed"
)

name2color <- c(
  "TCGA: Lung cancer" = "#56B4E9",
  "tcga:tcga-luad" = "#56B4E9",
  "tcga:tcga-luad-tumor" = "#56B4E9", # #D55E00
  "TCGA: Breast cancer" = "#0072B2",
  "TCGA: Breast c." = "#0072B2",
  "tcga:tcga-brca_female" = "#0072B2",
  "tcga:tcga-brca-tumor_female" = "#0072B2",
  "breast neoplasms"="#0072B2", 
  "gse193677" = "#E032EC",
  "GSE193677" = "#E032EC",
  "gse193677:rectum_uc_inflamed" = "#E032EC",
  "UC inflamed" = "#E032EC",
  "GTEx: Whole blood" = "#65F3BF",
  "gtex:whole.blood" = "#65F3BF",
  "GTEx: Lung" = "#077d2b",
  "gtex:lung" = "#077d2b",
  "GTEx: Breast" = "#00BA37", #44AA99
  "gtex:breast.mammary.tissue" = "#00BA37",
  "gtex:breast.mammary.tissue_female" = "#00BA37",
  "R. arthritis" = "#D55E00", #E69F00
  "scipher:scipher.sample.per.patient.baseline" = "#D55E00",
  "arthritis rheumatoid"="#D55E00", 
  "asthma"="#d9f365", 
  "thyroid neoplasms"="#0072B2",
  "tcga" = "#0072B2",
  "TCGA" = "#0072B2",
  "gtex" = "#00BA37",
  "GTEx" = "#00BA37",
  "scipher" = "#D55E00",
  #"Analytical model"="#e3f705",
  "Analytical model"="#cc68f7",
  "Power law"="#cc68f7",
  "Logarithm"="#09b863",
  "Exponential decay"="#09b863",
  "\u2265 0.2" = "#F8766D",
  "\u2265 0.4" = "#7CAE00",
  "\u2265 0.6" = "#00BFC4",
  "\u2265 0.8" = "#C77CFF",
  "Very Weak" = "#ff7b00",
  "Weak" = "#F8766D",
  "Moderate" = "#7CAE00",
  "Strong" = "#00BFC4",
  "Very Strong" = "#C77CFF",
  "Convergence point" = "red",
  "Model prediction" = "red",
  "P-value < 0.05" = "red",
  "common" = "#619CFF",
  "disease-gene" = "#cc68f7",
  "disease-specific" = "#F8766D",
  "normal-specific" = "#00BA38",
  "undefined" = "#808080",
  "different" = "#C77CFF",
  "all" = "#CD9600",
  "common (constant)" = "#619CFF",
  "common (change)" = "#b5d1ff",
  "disease-specific (constant)" = "#F8766D",
  "disease-specific (change)" = "#ffcbc7",
  "normal-specific (constant)" = "#00BA38",
  "normal-specific (change)" = "#a3d1b1",
  "undefined (constant)" = "#808080",
  "undefined (change)" = "#c2c2c2"
  )
```

## Aracne analysis

```{r define_params_analysis_strong_scores}
dataset_to_file_names <- list(
  "tcga:tcga-brca_female" = "/scratch/j.aguirreplans/Scipher/SampleSizeProject/networks_tcga/reads/tumor/tcga_TCGA-BRCA_female",
  "gtex:lung" = "/scratch/j.aguirreplans/Scipher/SampleSizeProject/networks_gtex/reads/gtex_Lung",
  "gtex:breast.mammary.tissue_female" = "/scratch/j.aguirreplans/Scipher/SampleSizeProject/networks_gtex/reads/gtex_Breast.Mammary.Tissue",
  "gse193677:rectum_uc_inflamed" = "/scratch/j.aguirreplans/Scipher/SampleSizeProject/networks_geo/GSE193677/reads/disease_inflamed_vs_control/gse193677_Rectum_UC_inflamed"
)
methods_selected <- c("pearson", "spearman", "aracne", "genie3")
method_to_thresholds <- list(
  "pearson" = c(0.6),
  "spearman" = c(0.6),
  "aracne" = c(1),
  "genie3" = c(0.01)
)
```

```{r calculate_percentage_strong_scores}
perc_strong_scores_file <- "/home/j.aguirreplans/Projects/Scipher/SampleSize/data/out/tables/analysis_percentage_strong_scores_filtered.txt"
strong_scores_results_df <- data.frame()
if (!(file.exists(perc_strong_scores_file)))  {
  for (method_sel in methods_selected) {
    for (threshold_sel in method_to_thresholds[[method_sel]]) {
      for (type_dataset_sel in names(dataset_to_file_names)) {
  
        # Read filtered networks
        merged_networks_file <- paste(
          dataset_to_file_names[[type_dataset_sel]],
          "_",
          method_sel,
          "_combined_filtered_by_threshold_",
          threshold_sel,
          ".txt",
          sep = "")
        if (file.exists(merged_networks_file)) {
          networks_df <- data.table::fread(merged_networks_file, header = TRUE)
  
          # Calculate the percentage of non-zero values in each column
          cols <- colnames(networks_df)
          score_cols <- cols[!(cols %in% c("Node.1", "Node.2"))]
          if (threshold_sel == 0) {
            strong_scores_subset_df <- as.data.frame(colSums(abs(networks_df[, ..score_cols]) > threshold_sel) / nrow(networks_df[, ..score_cols]) * 100)
          } else {
            strong_scores_subset_df <- as.data.frame(colSums(abs(networks_df[, ..score_cols]) >= threshold_sel) / nrow(networks_df[, ..score_cols]) * 100)
          }
          strong_scores_subset_df$ss.rep <- row.names(strong_scores_subset_df)
          row.names(strong_scores_subset_df) <- NULL
          colnames(strong_scores_subset_df) <- c("percentage_above_threshold", "ss.rep")
          strong_scores_subset_df <- strong_scores_subset_df %>%
            tidyr::separate("ss.rep", into=c("ss", "rep"), sep="[.]") %>%
            dplyr::mutate(
              ss = as.numeric(ss),
              rep = as.numeric(rep),
              method = method_sel,
              threshold = threshold_sel,
              type_dataset = type_dataset_sel
            )
      
          strong_scores_results_df <- rbind(
            strong_scores_results_df,
            strong_scores_subset_df
          )
          rm(networks_df)
        } else {
          print(paste("The following merged networks file does not exist:", merged_networks_file))
        }
      }
    } 
  }
  strong_scores_results_df %>% data.table::fwrite(perc_strong_scores_file, sep = "\t")
} else {
  strong_scores_results_df <- data.table::fread(perc_strong_scores_file, header = TRUE)
}
head(strong_scores_results_df)
```

```{r calculate_percentage_remaining_strong_scores}
perc_remaining_strong_scores_file <- "/home/j.aguirreplans/Projects/Scipher/SampleSize/data/out/tables/analysis_percentage_remaining_strong_scores_filtered.txt"
large_sample_columns <- c("120.1", "120.2", "120.3", "120.4", "120.5")
score_threshold <- 0.6
perc_remaining_strong_scores_df <- data.frame()
sd_df <- data.frame()
if (!(file.exists(perc_remaining_strong_scores_file))) {
  for (method_sel in methods_selected) {
    threshold_sel <- method_to_thresholds[[method_sel]]
    for (type_dataset_sel in names(dataset_to_file_names)) {

      # Read filtered networks
      merged_networks_file <- paste(
        dataset_to_file_names[[type_dataset_sel]],
        "_",
        method_sel,
        "_combined_filtered_by_threshold_",
        threshold_sel,
        ".txt",
        sep = "")
  
      # Read networks and filter by strong correlations in the largest sample size
      networks_df <- data.table::fread(merged_networks_file, header = TRUE) %>%
        dplyr::filter(dplyr::if_all(large_sample_columns, ~ abs(.) >= abs(score_threshold)))
  
      # Select 100k interactions randomly
      networks_df <- networks_df[row.names(networks_df) %in% sample(row.names(networks_df), size=100000, replace=FALSE),] # Check example with less edges
    
      # Transform data frame into long format
      networks_df <- networks_df %>%
        dplyr::mutate(gp = paste(Node.1, Node.2, sep = " -- ")) %>%
        dplyr::select(!(c(Node.1, Node.2))) %>%
        tidyr::pivot_longer(!gp, names_to = "ss.rep", values_to = "correlation") %>%
        tidyr::separate("ss.rep", into=c("ss", "rep"), sep="[.]") %>%
        dplyr::mutate(ss = as.numeric(ss), rep = as.numeric(rep))
    
      # Calculate the percentage of strong correlations by sample size
      perc_strong_corr_dataset_df <- networks_df %>%
        dplyr::group_by(gp, ss) %>%
        dplyr::summarize(mean_corr = mean(correlation)) %>%
        dplyr::ungroup() %>%
        dplyr::group_by(gp) %>%
        mutate(
          corr_max_ss = mean_corr[ss == max(ss)],
          diff = abs((corr_max_ss - mean_corr)) 
        ) %>%
        ungroup() %>%
        dplyr::group_by(ss) %>%
        dplyr::summarize(
          num_strong_corr = sum(abs(mean_corr) >= abs(score_threshold)),
          perc_strong_corr = num_strong_corr / n() * 100,
          mean_diff = mean(diff)
        ) %>%
        dplyr::ungroup() %>%
        dplyr::mutate(type_dataset = type_dataset_sel)
  
      perc_remaining_strong_scores_df <- rbind(
        perc_remaining_strong_scores_df,
        perc_strong_corr_dataset_df
      )
    }
  }

  perc_remaining_strong_scores_df %>% data.table::fwrite(perc_remaining_strong_scores_file, sep = "\t")

} else {
  perc_remaining_strong_scores_df <- data.table::fread(perc_remaining_strong_scores_file, header = TRUE)
}
```


```{r plot_aracne_strong_scores}
if (!("rgb_col" %in% colnames(strong_scores_results_df))) {
  strong_scores_results_df <- strong_scores_results_df %>%
    inner_join( (name2color %>% 
                   as.data.frame() %>% 
                   dplyr::rename("rgb_col"=".") %>% 
                   tibble::rownames_to_column("type_dataset")), 
                by=c("type_dataset") ) %>%
    dplyr::mutate(
      ss = as.numeric(ss),
      type_dataset = dplyr::recode(type_dataset, !!!dataset2name)
    )
}

aracne_strong_scores_df <- strong_scores_results_df %>%
  dplyr::filter(method == "aracne") %>%
  dplyr::group_by(threshold, type_dataset, rgb_col, ss) %>%
  dplyr::summarize(mean_percentage_above_threshold = mean(percentage_above_threshold)) %>%
  dplyr::mutate(threshold = as.character(threshold))

aracne_strong_scores_plot <- aracne_strong_scores_df %>%
  ggplot(aes(x = ss, y = mean_percentage_above_threshold)) +
  geom_line(aes(col = rgb_col, linetype = threshold), size = 1) +
  scale_colour_identity(
    labels = unique(aracne_strong_scores_df$type_dataset),
    breaks = unique(aracne_strong_scores_df$rgb_col),
    guide = "legend"
  ) +
  xlab("Num. samples") +
  ylab("% interactions above threshold") +
  guides(col=guide_legend(title="Dataset")) +
  theme_linedraw() +
  theme(aspect.ratio = 1, 
        plot.title = element_text(size = 20, face = "bold"), 
        axis.title = element_text(size = 17, face = "bold"), 
        axis.text = element_text(size = 16), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        text = element_text(family = font_selected),
        legend.text = element_text(size = 16), 
        legend.title=element_text(size=16, face="bold")
  )
print(aracne_strong_scores_plot)
```

```{r plot_genie3_strong_scores}
if (!("rgb_col" %in% colnames(strong_scores_results_df))) {
  strong_scores_results_df <- strong_scores_results_df %>%
    inner_join( (name2color %>% 
                   as.data.frame() %>% 
                   dplyr::rename("rgb_col"=".") %>% 
                   tibble::rownames_to_column("type_dataset")), 
                by=c("type_dataset") ) %>%
    dplyr::mutate(
      ss = as.numeric(ss),
      type_dataset = dplyr::recode(type_dataset, !!!dataset2name)
    )
}

genie3_strong_scores_df <- strong_scores_results_df %>%
  dplyr::filter(method == "genie3") %>%
  dplyr::group_by(threshold, type_dataset, rgb_col, ss) %>%
  dplyr::summarize(mean_percentage_above_threshold = mean(percentage_above_threshold)) %>%
  dplyr::mutate(threshold = as.character(threshold))

genie3_strong_scores_plot <- genie3_strong_scores_df %>%
  ggplot(aes(x = ss, y = mean_percentage_above_threshold)) +
  geom_line(aes(col = rgb_col), size = 1) +
  scale_colour_identity(
    labels = unique(genie3_strong_scores_df$type_dataset),
    breaks = unique(genie3_strong_scores_df$rgb_col),
    guide = "legend"
  ) +
  xlab("Num. samples") +
  ylab("% interactions above 0.01") +
  guides(col=guide_legend(title="Dataset")) +
  theme_linedraw() +
  theme(aspect.ratio = 1, 
        plot.title =  element_text(size = 20, face = "bold"), 
        axis.title = element_text(size = 17, face = "bold"), 
        axis.text = element_text(size = 16), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        text = element_text(family = font_selected),
        legend.text = element_text(size = 16), 
        legend.title=element_text(size=16, face="bold")
  )
print(genie3_strong_scores_plot)
```

```{r plot_all_methods_strong_scores}
if (!("rgb_col" %in% colnames(strong_scores_results_df))) {
  strong_scores_results_df <- strong_scores_results_df %>%
    inner_join( (name2color %>% 
                   as.data.frame() %>% 
                   dplyr::rename("rgb_col"=".") %>% 
                   tibble::rownames_to_column("type_dataset")), 
                by=c("type_dataset") ) %>%
    dplyr::mutate(
      ss = as.numeric(ss),
      type_dataset = dplyr::recode(type_dataset, !!!dataset2name)
    )
}

for (type_dataset_sel in unique(strong_scores_results_df$type_dataset)) {
  strong_scores_by_method_df <- strong_scores_results_df %>%
    dplyr::filter(!((method == "aracne") & (threshold == 0))) %>%
    dplyr::filter(type_dataset == type_dataset_sel) %>%
    dplyr::group_by(threshold, method, ss) %>%
    dplyr::summarize(mean_percentage_above_threshold = mean(percentage_above_threshold)) %>%
    dplyr::mutate(threshold = as.character(threshold))
  
  strong_scores_by_method_plot <- strong_scores_by_method_df %>%
    ggplot(aes(x = ss, y = mean_percentage_above_threshold)) +
    geom_line(aes(col = method), size = 1) +
    xlab("Num. samples") +
    ylab("% interactions above threshold") +
    guides(col=guide_legend(title="Method")) +
    theme_linedraw() +
    theme(aspect.ratio = 1, 
          plot.title =  element_text(size = 20, face = "bold"), 
          axis.title = element_text(size = 17, face = "bold"), 
          axis.text = element_text(size = 16), 
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          text = element_text(family = font_selected),
          legend.text = element_text(size = 16), 
          legend.title=element_text(size=16, face="bold")
    )
  print(strong_scores_by_method_plot)
}
```



